name: Package Auto-StockTrader

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: Prem-ium/Auto-StockTrader

    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Configure
      run: |
        ren .env.example .env
        get-content .env | %{$_ -replace "C:\\Users\\Premium\\Desktop\\CodingProjects\\SeleniumFolder",".\"}
        
    - name: Build .side file
      run: |
        python main.py

