name: Package Auto-StockTrader

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: debilin/Auto-StockTrader
        ref: main

    - name: Install dependencies
      run: pip install -r requirements.txt
        
    - name: Configure
      run: |
        mkdir dist
#        get-content .env.example | %{$_ -replace "C:\\Users\\Premium\\Desktop\\CodingProjects\\SeleniumFolder","$pwd\dist"}
#        Get-ChildItem -Path $pwd -Recurse | Where-Object {$_.PSIsContainer -eq $false}  
    
    - name: 'Create env file'
      run: |
        touch .env
        echo CHASE_AI= >> .env
        echo CUSTOM_DIR='$pwd\dist' >> .env
        cat .env

    - name: Build .side file
      run: |
        ren .env.example .env.test
        python main.py

